class TransformerInfo {
  final String number;
  final String voltage;
  final String? serial;
  final String? manufacturer;
  final String? mva;
  final String? yearManufacture;

  const TransformerInfo({
    required this.number,
    required this.voltage,
    this.serial,
    this.manufacturer,
    this.mva,
    this.yearManufacture,
  });

  String get effectiveYearManufacture {
    if (yearManufacture != null && yearManufacture!.trim().isNotEmpty) {
      return yearManufacture!.trim();
    }
    if (serial != null && serial!.isNotEmpty) {
      final match = RegExp(r'(19\d\d|20\d\d)').firstMatch(serial!);
      if (match != null) {
        return match.group(1)!;
      }
    }
    return '';
  }
}

class SubstationModel {
  final String id;
  final String name;
  final String region;
  final String division;
  final String department;
  final List<TransformerInfo> transformers;
  final List<TransformerInfo> auxTransformers;

  const SubstationModel({
    required this.id,
    required this.name,
    required this.region,
    this.division = 'SOD / Southern Operating Division',
    this.department = 'Substation Maintenance Dept',
    required this.transformers,
    this.auxTransformers = const [],
  });
}

class NationalGridData {
  static const List<String> divisions = [
    'SOD / Southern Operating Division',
    'WOD / Western Operating Division',
    'EOD / Eastern Operating Division',
    'COA / Central Operating Area',
  ];

  static const Map<String, List<String>> departments = {
    'SOD / Southern Operating Division': [
      'Substation Maintenance Dept',
      'Transmission Lines Dept',
      'Protection & Control Dept',
      'Communication Dept',
    ],
    'WOD / Western Operating Division': [
      'Substation Maintenance Dept - West',
      'Transmission Lines Dept - West',
      'Protection Dept - West',
    ],
    'EOD / Eastern Operating Division': [
      'Substation Maintenance Dept - East',
      'Transmission Lines Dept - East',
    ],
    'COA / Central Operating Area': [
      'Substation Maintenance Dept - Central',
      'Transmission Lines Dept - Central',
    ],
  };

  static List<String> get allDivisions => divisions;

  static List<String> get allDepartments {
    final all = <String>{};
    for (final deptList in departments.values) {
      all.addAll(deptList);
    }
    return all.toList();
  }

  static List<String> getDepartmentsForDivision(String division) {
    return departments[division] ?? ['Substation Maintenance Dept'];
  }

  static const List<SubstationModel> substations = [
    SubstationModel(
      id: 'sub_1',
      name: 'JIC',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8 Kv',
          serial: '54190',
          manufacturer: 'BEST',
          mva: '67',
          yearManufacture: '2009',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8 Kv',
          serial: '54191',
          manufacturer: 'BEST',
          mva: '67',
          yearManufacture: '2009',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8 Kv',
          serial: '54192',
          manufacturer: 'BEST',
          mva: '67',
          yearManufacture: '2009',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_2',
      name: 'Atuwal',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '20090519TGC010-001',
          manufacturer: 'Hyundai',
          mva: '67',
          yearManufacture: '2009',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '20090519TGC010-002',
          manufacturer: 'Hyundai',
          mva: '67',
          yearManufacture: '2009',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_3',
      name: 'Kudmi',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T801',
          voltage: '380/132/13.8',
          serial: '316950',
          manufacturer: 'AREVA',
          mva: '502',
          yearManufacture: '2008',
        ),
        TransformerInfo(
          number: 'T802',
          voltage: '380/132/13.8',
          serial: '316951',
          manufacturer: 'AREVA',
          mva: '502',
          yearManufacture: '2008',
        ),
        TransformerInfo(
          number: 'T803',
          voltage: '380/132/13.8',
          serial: 'PA006-01',
          manufacturer: 'ALSTOM',
          mva: '502',
          yearManufacture: '2014',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_4',
      name: 'Ayban',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/33/13.8',
          serial: '317379',
          manufacturer: 'Areva',
          mva: '133',
          yearManufacture: '2009',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/33/13.8',
          serial: '317378',
          manufacturer: 'Areva',
          mva: '133',
          yearManufacture: '2009',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_5',
      name: 'Gizan North',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: 'D416800',
          manufacturer: 'Siemens',
          mva: '67',
          yearManufacture: '2008',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: 'D416801',
          manufacturer: 'Siemens',
          mva: '67',
          yearManufacture: '2008',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8',
          serial: '318263',
          manufacturer: 'ALSTOM',
          mva: '67',
          yearManufacture: '2015',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_6',
      name: 'Baish',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/33/13.8',
          serial: '316948',
          manufacturer: 'AREVA',
          mva: '133',
          yearManufacture: '2006',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/33/13.8',
          serial: '316949',
          manufacturer: 'AREVA',
          mva: '133',
          yearManufacture: '2006',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_7',
      name: 'KFH',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: 'D416802',
          manufacturer: 'Siemens',
          mva: '67',
          yearManufacture: '2008',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: 'D416803',
          manufacturer: 'Siemens',
          mva: '67',
          yearManufacture: '2008',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_8',
      name: 'Ad-Dayar',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/33/13.8',
          serial: '317377',
          manufacturer: 'AREVA',
          mva: '133',
          yearManufacture: '2009',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/33/13.8',
          serial: '317376',
          manufacturer: 'AREVA',
          mva: '133',
          yearManufacture: '2009',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_9',
      name: 'Salama',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '5.4.0504',
          manufacturer: 'PAUWELS',
          mva: '67',
          yearManufacture: '2006',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '5.4.0505',
          manufacturer: 'PAUWELS',
          mva: '67',
          yearManufacture: '2006',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8',
          serial: '5.4.0506',
          manufacturer: 'PAUWELS',
          mva: '67',
          yearManufacture: '2006',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_10',
      name: 'Sabya North',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '05.4.0510',
          manufacturer: 'PAUWELS',
          mva: '67',
          yearManufacture: '2006',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/33/13.8',
          serial: '49603',
          manufacturer: 'BEST',
          mva: '133',
          yearManufacture: '2007',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/33/13.8',
          serial: '49602',
          manufacturer: 'BEST',
          mva: '133',
          yearManufacture: '2007',
        ),
        TransformerInfo(
          number: 'T604',
          voltage: '132/13.8',
          serial: '05.4.0508',
          manufacturer: 'PAUWELS',
          mva: '67',
          yearManufacture: '2006',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_11',
      name: 'Gizan South',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '05.4.0507',
          manufacturer: 'PAUWELS',
          mva: '67',
          yearManufacture: '2006',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/33/13.8',
          serial: '49600',
          manufacturer: 'BEST',
          mva: '133',
          yearManufacture: '2007',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/33/13.8',
          serial: '49601',
          manufacturer: 'BEST',
          mva: '133',
          yearManufacture: '2007',
        ),
        TransformerInfo(
          number: 'T604',
          voltage: '132/13.8',
          serial: '05.4.0509',
          manufacturer: 'PAUWELS',
          mva: '67',
          yearManufacture: '2006',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_12',
      name: 'Jazan CPS2',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/33/13.8',
          serial: '05.4.0513',
          manufacturer: 'PAUWELS',
          yearManufacture: '2005',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/33/13.8',
          serial: '05.4.0514',
          manufacturer: 'PAUWELS',
          yearManufacture: '2005',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_13',
      name: 'Jazan CPS1',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601 ( IBT10 )',
          voltage: '132/33',
          serial: '12145794',
          manufacturer: 'ASEA',
          mva: '80',
          yearManufacture: '1985',
        ),
        TransformerInfo(
          number: 'T606 ( IBT12 )',
          voltage: '132/33',
          serial: '90.4.1520',
          manufacturer: 'PAUWELS',
          yearManufacture: '1991',
        ),
        TransformerInfo(
          number: 'T602 ( IBT11 )',
          voltage: '132/33',
          serial: '12145793',
          manufacturer: 'ASEA',
          mva: '80',
          yearManufacture: '1985',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_14',
      name: 'Ad-Darb',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601(T1)',
          voltage: '132/33',
          serial: '94-4-0038',
          manufacturer: 'PAUWELS',
          mva: '83',
          yearManufacture: '1994',
        ),
        TransformerInfo(
          number: 'T602(T2)',
          voltage: '132/33',
          serial: '94-4-0037',
          manufacturer: 'PAUWELS',
          mva: '83',
          yearManufacture: '1994',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_15',
      name: 'Al Ahad',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601(T1)',
          voltage: '132/33',
          serial: '1ZTR241701',
          manufacturer: 'ABB',
          mva: '133',
          yearManufacture: '2004',
        ),
        TransformerInfo(
          number: 'T602(T2)',
          voltage: '132/33',
          serial: '1ZTR241702',
          manufacturer: 'ABB',
          mva: '133',
          yearManufacture: '2004',
        ),
        TransformerInfo(
          number: 'T1  (T405)',
          voltage: '33/13.8',
          serial: '280175/01',
          manufacturer: 'AREVA',
          mva: '20',
          yearManufacture: '2007',
        ),
        TransformerInfo(
          number: 'T2 (T404)',
          voltage: '33/13.8',
          serial: '280176/01',
          manufacturer: 'AREVA',
          mva: '20',
          yearManufacture: '2007',
        ),
        TransformerInfo(
          number: 'T3 (T403)',
          voltage: '33/13.8',
          serial: '280177/01',
          manufacturer: 'AREVA',
          mva: '20',
          yearManufacture: '2007',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_16',
      name: 'Zarga',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601(T1)',
          voltage: '132/33/13.8',
          serial: '03.4.0216',
          manufacturer: 'PAUWELS',
          mva: '133',
          yearManufacture: '2003',
        ),
        TransformerInfo(
          number: 'T602(T2)',
          voltage: '132/33/13.8',
          serial: '04.4.0432',
          manufacturer: 'PAUWELS',
          mva: '133',
          yearManufacture: '2005',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_17',
      name: 'Samitah',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T603(T3)',
          voltage: '132/33/13.8',
          serial: '90.4.1522',
          manufacturer: 'PAUWELS',
          mva: '133',
          yearManufacture: '1991',
        ),
        TransformerInfo(
          number: 'T602(T2)',
          voltage: '132/33/13.8',
          serial: '90.4.1521',
          manufacturer: 'PAUWELS',
          mva: '133',
          yearManufacture: '1991',
        ),
        TransformerInfo(
          number: 'T604(T1)',
          voltage: '132/13.8',
          serial: 'D416378',
          manufacturer: 'SIEMENS',
          mva: '60',
          yearManufacture: '2004',
        ),
        TransformerInfo(
          number: 'T601(T4)',
          voltage: '132/13.8',
          serial: 'D416379',
          manufacturer: 'SIEMENS',
          mva: '60',
          yearManufacture: '2004',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_18',
      name: 'Abu-Areish South',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601(T2)',
          voltage: '132/33/13.8',
          serial: '90.4.1517',
          manufacturer: 'PAUWELS',
          mva: '133',
          yearManufacture: '1991',
        ),
        TransformerInfo(
          number: 'T602(T3)',
          voltage: '132/33/13.8',
          serial: '90.4.1516',
          manufacturer: 'PAUWELS',
          mva: '133',
          yearManufacture: '1991',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_19',
      name: 'Al-Haqu',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T602(T-3)',
          voltage: '132/33',
          serial: '92.4.4121',
          manufacturer: 'PAUWELS',
          mva: '83',
          yearManufacture: '1993',
        ),
        TransformerInfo(
          number: 'T601(T-2)',
          voltage: '132/33',
          serial: '92.4.4122',
          manufacturer: 'PAUWELS',
          mva: '83',
          yearManufacture: '1993',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_20',
      name: 'Abu Qaeed',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/33',
          serial: '318042',
          manufacturer: 'ALSTOM',
          mva: '133',
          yearManufacture: '2013',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/33',
          serial: '318043',
          manufacturer: 'ALSTOM',
          mva: '133',
          yearManufacture: '2013',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_21',
      name: 'Abu Sadad',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '64003',
          manufacturer: 'BEST',
          mva: '67',
          yearManufacture: '2013',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '64004',
          manufacturer: 'BEST',
          mva: '67',
          yearManufacture: '2013',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/33',
          serial: '64001',
          manufacturer: 'BEST',
          mva: '83',
          yearManufacture: '2013',
        ),
        TransformerInfo(
          number: 'T604',
          voltage: '132/33',
          serial: '64002',
          manufacturer: 'BEST',
          mva: '83',
          yearManufacture: '2013',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_22',
      name: 'Al-Khishl New',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/33',
          serial: 'D417790',
          manufacturer: 'SIEMENS',
          mva: '100',
          yearManufacture: '2014',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/33',
          serial: 'D417789',
          manufacturer: 'SIEMENS',
          mva: '100',
          yearManufacture: '2014',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_23',
      name: 'Iskan',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/33',
          serial: '20112077TGC021-002',
          manufacturer: 'Hyundai',
          mva: '83',
          yearManufacture: '2012',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '20112077TGC020-001',
          manufacturer: 'Hyundai',
          mva: '67',
          yearManufacture: '2012',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8',
          serial: '20112077TGC020-002',
          manufacturer: 'Hyundai',
          mva: '67',
          yearManufacture: '2012',
        ),
        TransformerInfo(
          number: 'T604',
          voltage: '132/33',
          serial: '20112077TGC021-001',
          manufacturer: 'Hyundai',
          mva: '83',
          yearManufacture: '2012',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_24',
      name: 'Jizan City Center',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '1ZTR141501',
          manufacturer: 'ABB',
          mva: '67',
          yearManufacture: '2016',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '1ZTR141502',
          manufacturer: 'ABB',
          mva: '67',
          yearManufacture: '2016',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8',
          serial: '1ZTR141503',
          manufacturer: 'ABB',
          mva: '67',
          yearManufacture: '2016',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_25',
      name: 'Jizan Economic City',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T801',
          voltage: '380/132/13.8',
          serial: '20092493TNF006-001',
          manufacturer: 'Hyundai',
          mva: '502',
          yearManufacture: '2010',
        ),
        TransformerInfo(
          number: 'T802',
          voltage: '380/132/13.8',
          serial: '20092493TNF006-002',
          manufacturer: 'Hyundai',
          mva: '502',
          yearManufacture: '2010',
        ),
        TransformerInfo(
          number: 'T803',
          voltage: '380/132/13.8',
          serial: 'PA113-01',
          manufacturer: 'ALSTOM',
          mva: '502',
          yearManufacture: '2016',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_26',
      name: 'Madhaya',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T801',
          voltage: '380/132/13.8',
          serial: 'PA021-01',
          manufacturer: 'ALSTOM',
          mva: '502',
          yearManufacture: '2015',
        ),
        TransformerInfo(
          number: 'T802',
          voltage: '380/132/13.8',
          serial: 'PA021-02',
          manufacturer: 'ALSTOM',
          mva: '502',
          yearManufacture: '2015',
        ),
        TransformerInfo(
          number: 'T803',
          voltage: '380/132/13.8',
          serial: 'PA021-03',
          manufacturer: 'ALSTOM',
          mva: '502',
          yearManufacture: '2015',
        ),
        TransformerInfo(
          number: 'T601',
          voltage: '132/33',
          serial: 'PA021-04',
          manufacturer: 'ALSTOM',
          mva: '100',
          yearManufacture: '2015',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/33',
          serial: 'PA021-05',
          manufacturer: 'ALSTOM',
          mva: '100',
          yearManufacture: '2015',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_27',
      name: 'Medical City',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '20114001TGC039-001',
          manufacturer: 'Hyundai',
          mva: '67',
          yearManufacture: '2012',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '20114001TGC039-002',
          manufacturer: 'Hyundai',
          mva: '67',
          yearManufacture: '2012',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8',
          serial: '20114001TGC039-003',
          manufacturer: 'Hyundai',
          mva: '67',
          yearManufacture: '2012',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_28',
      name: 'Mokhtara',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '20141377TGC032-001',
          manufacturer: 'Hyundai',
          mva: '67',
          yearManufacture: '2015',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '20141377TGC032-002',
          manufacturer: 'Hyundai',
          mva: '67',
          yearManufacture: '2015',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8',
          serial: '20141377TGC032-003',
          manufacturer: 'Hyundai',
          mva: '67',
          yearManufacture: '2015',
        ),
        TransformerInfo(
          number: 'T604',
          voltage: '132/33',
          serial: '20141377TGC033-001',
          manufacturer: 'Hyundai',
          mva: '100',
          yearManufacture: '2015',
        ),
        TransformerInfo(
          number: 'T605',
          voltage: '132/33',
          serial: '20141377TGC033-002',
          manufacturer: 'Hyundai',
          mva: '100',
          yearManufacture: '2015',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_29',
      name: 'Shuqiq 380KV',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T801',
          voltage: '380/132/13.8',
          serial: '317206',
          manufacturer: 'AREVA',
          mva: '502',
          yearManufacture: '2008',
        ),
        TransformerInfo(
          number: 'T802',
          voltage: '380/132/13.8',
          serial: '317205',
          manufacturer: 'AREVA',
          mva: '502',
          yearManufacture: '2008',
        ),
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '317203',
          manufacturer: 'AREVA',
          mva: '67',
          yearManufacture: '2008',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '317204',
          manufacturer: 'AREVA',
          mva: '67',
          yearManufacture: '2008',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_30',
      name: 'University',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: 'D417604',
          manufacturer: 'SIEMENS',
          mva: '67',
          yearManufacture: '2012',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: 'D417605',
          manufacturer: 'SIEMENS',
          mva: '67',
          yearManufacture: '2012',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8',
          serial: 'D417606',
          manufacturer: 'SIEMENS',
          mva: '67',
          yearManufacture: '2012',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_31',
      name: 'Aridhah',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/33',
          serial: '5337PA096-07',
          manufacturer: 'GE',
          mva: '100',
          yearManufacture: '2016',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/33',
          serial: '5337PA096-08',
          manufacturer: 'GE',
          mva: '100',
          yearManufacture: '2016',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/33',
          serial: '5337PA096-09',
          manufacturer: 'GE',
          mva: '100',
          yearManufacture: '2016',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_32',
      name: 'Phase 1',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '5337PA195-01',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2019',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '5337PA195-02',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2019',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/33',
          serial: '5337PA195-06',
          manufacturer: 'GE',
          mva: '100',
          yearManufacture: '2018',
        ),
        TransformerInfo(
          number: 'T604',
          voltage: '132/33',
          serial: '5337PA195-0',
          manufacturer: 'GE',
          mva: '100',
          yearManufacture: '2018',
        ),
        TransformerInfo(
          number: 'T605',
          voltage: '132/33',
          serial: '5337PA195-07',
          manufacturer: 'GE',
          mva: '100',
          yearManufacture: '2018',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_33',
      name: 'Jizan City Center 2',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '5337PA170-01',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2019',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '5337PA170-02',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2019',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8',
          serial: '5337PA170-03',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2019',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_34',
      name: 'Baish west',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '5337PA158-11',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2017',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '5337PA158-12',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2017',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8',
          serial: '5337PA158-13',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2017',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_35',
      name: 'Sabya West',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '5337PA096-04',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2016',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '5337PA096-05',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2016',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8',
          serial: '5337PA096-06',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2016',
        ),
        TransformerInfo(
          number: 'T604',
          voltage: '132/33',
          serial: '5337PA096-10',
          manufacturer: 'GE',
          mva: '100',
          yearManufacture: '2016',
        ),
        TransformerInfo(
          number: 'T605',
          voltage: '132/33',
          serial: '5337PA096-11',
          manufacturer: 'GE',
          mva: '100',
          yearManufacture: '2016',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_36',
      name: 'RC',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: '5337PA195-03',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2019',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: '5337PA195-03',
          manufacturer: 'GE',
          mva: '67',
          yearManufacture: '2019',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_37',
      name: 'Al Aseelah',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T801',
          voltage: '380/132/13.8',
          serial: '10157559_0001',
          manufacturer: 'HYOSUNG CORPORATION',
          mva: '502',
          yearManufacture: '4٫2021',
        ),
        TransformerInfo(
          number: 'T802',
          voltage: '380/132/13.8',
          serial: '10157559_002',
          manufacturer: 'HYOSUNG CORPORATION',
          mva: '502',
          yearManufacture: '4٫2021',
        ),
        TransformerInfo(
          number: 'T803',
          voltage: '380/132/13.8',
          serial: '10157559_0003',
          manufacturer: 'HYOSUNG CORPORATION',
          mva: '502',
          yearManufacture: '4٫2021',
        ),
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: 'S08201DD26',
          manufacturer: 'SPTC',
          mva: '67',
          yearManufacture: '2021',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: 'S08201DD27',
          manufacturer: 'SPTC',
          mva: '67',
          yearManufacture: '2021',
        ),
        TransformerInfo(
          number: 'T603',
          voltage: '132/13.8',
          serial: 'S08201DD28',
          manufacturer: 'SPTC',
          mva: '67',
          yearManufacture: '2021',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_38',
      name: 'Port',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T601',
          voltage: '132/13.8',
          serial: 'S0120190007',
          manufacturer: 'SPTC',
          mva: '40',
          yearManufacture: '2019',
        ),
        TransformerInfo(
          number: 'T602',
          voltage: '132/13.8',
          serial: 'S0120190008',
          manufacturer: 'SPTC',
          mva: '40',
          yearManufacture: '2019',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_39',
      name: 'Mobiel  ( Towal )',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T622',
          voltage: '132/13.8',
          serial: '05P0054',
          manufacturer: 'PAUWELS',
          mva: '40',
          yearManufacture: '2006',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_40',
      name: 'Mobiel (Al Khishel)',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T623',
          voltage: '132/33',
          serial: '4004370',
          manufacturer: 'PAUWELS',
          mva: '40',
          yearManufacture: '2011',
        ),
        TransformerInfo(
          number: 'T624',
          voltage: '132/33',
          serial: '00.4.0076',
          manufacturer: 'PAUWELS',
          mva: '40',
          yearManufacture: '2001',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_41',
      name: 'Mobiel( Baish )',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T625',
          voltage: '132/33/13.8',
          serial: '137277',
          manufacturer: 'CG Electric System',
          mva: '40',
          yearManufacture: '2016',
        ),
      ],
    ),
    SubstationModel(
      id: 'sub_42',
      name: 'mobil  (Army)',
      region: 'JIZAN',
      division: 'SOD / Southern Operating Division',
      department: 'Substation Maintenance Dept',
      transformers: [
        TransformerInfo(
          number: 'T626',
          voltage: '132/13.8',
          serial: '00.4.00777',
          manufacturer: 'PAUWELS',
          mva: '40',
          yearManufacture: '2001',
        ),
      ],
    ),
  ];
}
